---
- name: Create folder and add layout.jade and homepage.jade
  hosts: dev
  # add remote_vars key and its value here

  vars_files:
    - basic.yaml
  tasks:
    - name: Ping the host
      ping:
    - name: create folder named with variable
      file:
        path: "{{main_dir}}/templates/{{folder_name}}"
        state: directory
    - name: create layout.jade file inside the folder
      template:
        src: "./layout.j2"
        dest: "{{main_dir}}/templates/{{folder_name}}/layout.jade"
    - name: create homepage.jade file inside the folder
      template:
        src: "./homepage.j2"
        dest: "{{main_dir}}/templates/{{folder_name}}/homepage.jade"